apiVersion: v1
kind: Secret
metadata:
  name: mall-secrets
  namespace: mall
type: Opaque
stringData:
  mysql-root-password: "Mall@2024!"
  mysql-password: "mall123"
  redis-password: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: mall-registry
  namespace: mall
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
