server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://47.108.130.167:13306/mall?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
