# ============================================
# 服务器部署环境 profile
# ============================================
spring:
  config:
    import: optional:nacos:application-common.yml
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: ${NACOS_SERVER}
      discovery:
        server-addr: ${NACOS_SERVER}
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}
      eager: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
      sentinel:
        enabled: true
  datasource:
    url: ${MYSQL_URL}
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
