spring:
  application:
    name: gateway
  profiles:
    active: local     # 默认本地，服务器启动时改为 -Dspring.profiles.active=server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates: [Path=/api/auth/**,/api/address/**]
          filters: [StripPrefix=1]
        - id: product-service
          uri: lb://product-service
          predicates: [Path=/api/product/**]
          filters: [StripPrefix=1]
        - id: order-service
          uri: lb://order-service
          predicates: [Path=/api/order/**]
          filters: [StripPrefix=1]
        - id: payment-service
          uri: lb://payment-service
          predicates: [Path=/api/payment/**]
          filters: [StripPrefix=1]
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
