spring:
  application:
    name: order-service
  profiles:
    active: local
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true  # 启动时即注册到 Dashboard

server:
  port: 8084

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
