spring:
  application:
    name: product-service
  profiles:
    active: local
  cache:
    type: redis
    redis:
      time-to-live: 300000  # 5分钟缓存

server:
  port: 8083

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
