spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER}
  datasource:
    url: ${MYSQL_URL}
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
